import { Activities } from "../../modules/interface";

export const activities: Activities[] = [
  {
    id: 1,
    title: "Visite guidée de Cambridge",
    description: "Visite guidée de l'université de Harvard pour les étudiants",
    duration: "70 minutes",
    rating: 4.6,
    reviews: 2934,
    price: "104,63 RM",
    image: "/images/cambridge.jpg",
  },
  {
    id: 2,
    title: "Tour de la ville de Paris",
    description:
      "Découverte des monuments emblématiques de Paris en bus touristique",
    duration: "2 heures",
    rating: 4.7,
    reviews: 1832,
    price: "75,00 EUR",
    image: "/images/paris.jpg",
  },
  {
    id: 3,
    title: "Excursion en bateau à Venise",
    description: "Croisière romantique à travers les canaux de Venise",
    duration: "1 heure 30 minutes",
    rating: 4.8,
    reviews: 2110,
    price: "55,00 EUR",
    image: "/images/venice.jpg",
  },
  {
    id: 4,
    title: "Safari dans le Serengeti",
    description:
      "Observation des grands animaux sauvages dans le parc national du Serengeti",
    duration: "4 heures",
    rating: 4.9,
    reviews: 1345,
    price: "220,00 USD",
    image: "/images/serengeti.jpg",
  },
  {
    id: 5,
    title: "Visite des pyramides d'Égypte",
    description:
      "Exploration des pyramides de Gizeh et de la grande pyramide de Khéops",
    duration: "3 heures",
    rating: 4.5,
    reviews: 2701,
    price: "150,00 USD",
    image: "/images/egypt.jpg",
  },
  {
    id: 6,
    title: "Dégustation de vin en Toscane",
    description: "Visite des vignobles et dégustation de vins en Toscane",
    duration: "5 heures",
    rating: 4.7,
    reviews: 1602,
    price: "120,00 EUR",
    image: "/images/tuscany.jpg",
  },
  {
    id: 7,
    title: "Plongée sous-marine à Bora Bora",
    description:
      "Expérience de plongée pour explorer les récifs coralliens de Bora Bora",
    duration: "2 heures",
    rating: 4.9,
    reviews: 1458,
    price: "200,00 USD",
    image: "/images/bora_bora.jpg",
  },
  {
    id: 8,
    title: "Randonnée dans les Alpes suisses",
    description: "Randonnée guidée à travers les paysages alpins suisses",
    duration: "6 heures",
    rating: 4.6,
    reviews: 1103,
    price: "85,00 CHF",
    image: "/images/alps.jpg",
  },
  {
    id: 9,
    title: "Visite du Grand Canyon",
    description: "Excursion en bus au Grand Canyon avec vue panoramique",
    duration: "3 heures",
    rating: 4.8,
    reviews: 1987,
    price: "90,00 USD",
    image: "/images/grand_canyon.jpg",
  },
  {
    id: 10,
    title: "Découverte de Tokyo",
    description:
      "Tour des attractions principales de Tokyo avec un guide local",
    duration: "4 heures",
    rating: 4.7,
    reviews: 1352,
    price: "80,00 JPY",
    image: "/images/tokyo.jpg",
  },
  {
    id: 11,
    title: "Croisière dans les fjords de Norvège",
    description: "Croisière spectaculaire dans les fjords norvégiens",
    duration: "5 heures",
    rating: 4.8,
    reviews: 1220,
    price: "150,00 NOK",
    image: "/images/norway.jpg",
  },
  {
    id: 12,
    title: "Visite guidée de Rome",
    description:
      "Tour des sites historiques de Rome avec un guide professionnel",
    duration: "3 heures",
    rating: 4.6,
    reviews: 1745,
    price: "95,00 EUR",
    image: "/images/rome.jpg",
  },
  {
    id: 13,
    title: "Excursion à Machu Picchu",
    description: "Visite guidée des ruines de Machu Picchu",
    duration: "4 heures",
    rating: 4.9,
    reviews: 1889,
    price: "220,00 PEN",
    image: "/images/machu_picchu.jpg",
  },
  {
    id: 14,
    title: "Découverte de Sydney",
    description:
      "Tour des attractions principales de Sydney, y compris l'Opéra",
    duration: "4 heures",
    rating: 4.7,
    reviews: 1408,
    price: "100,00 AUD",
    image: "/images/sydney.jpg",
  },
  {
    id: 15,
    title: "Visite de la Grande Muraille de Chine",
    description: "Excursion guidée sur la Grande Muraille de Chine",
    duration: "5 heures",
    rating: 4.8,
    reviews: 1635,
    price: "160,00 CNY",
    image: "/images/great_wall.jpg",
  },
  {
    id: 16,
    title: "Tour en hélicoptère à New York",
    description: "Vue panoramique de New York depuis un hélicoptère",
    duration: "30 minutes",
    rating: 4.9,
    reviews: 1450,
    price: "300,00 USD",
    image: "/images/new_york.jpg",
  },
  {
    id: 17,
    title: "Visite de la Sagrada Familia",
    description: "Tour guidé de la basilique Sagrada Familia à Barcelone",
    duration: "2 heures",
    rating: 4.7,
    reviews: 1293,
    price: "70,00 EUR",
    image: "/images/sagrada_familia.jpg",
  },
  {
    id: 18,
    title: "Excursion à la Cappadoce",
    description:
      "Vol en montgolfière et visite des formations rocheuses en Cappadoce",
    duration: "3 heures",
    rating: 4.8,
    reviews: 1111,
    price: "180,00 TRY",
    image: "/images/cappadocia.jpg",
  },
  {
    id: 19,
    title: "Détente à Bali",
    description: "Séjour relaxant dans un complexe balnéaire de Bali",
    duration: "3 jours",
    rating: 4.9,
    reviews: 2002,
    price: "500,00 USD",
    image: "/images/bali.jpg",
  },
  {
    id: 20,
    title: "Visite des chutes du Niagara",
    description: "Excursion en bateau pour voir les chutes du Niagara de près",
    duration: "2 heures",
    rating: 4.8,
    reviews: 1749,
    price: "85,00 CAD",
    image: "/images/niagara.jpg",
  },
];
