import { Flights } from "@/modules/interface";

export const flights: Flights[] = [
  {
    id: "FL001",
    airline: "Air France",
    departureCity: "Paris",
    arrivalCity: "New York",
    departureDate: "2024-09-01",
    departureTime: "10:30",
    arrivalTime: "13:30",
    duration: "8h",
    price: 450,
    availableSeats: 12,
  },
  {
    id: "FL002",
    airline: "Delta Airlines",
    departureCity: "New York",
    arrivalCity: "Los Angeles",
    departureDate: "2024-09-02",
    departureTime: "14:00",
    arrivalTime: "17:00",
    duration: "5h",
    price: 300,
    availableSeats: 20,
  },
  {
    id: "FL003",
    airline: "Lufthansa",
    departureCity: "Berlin",
    arrivalCity: "Tokyo",
    departureDate: "2024-09-03",
    departureTime: "06:00",
    arrivalTime: "22:00",
    duration: "14h",
    price: 950,
    availableSeats: 8,
  },
  {
    id: "FL004",
    airline: "British Airways",
    departureCity: "London",
    arrivalCity: "Dubai",
    departureDate: "2024-09-04",
    departureTime: "09:00",
    arrivalTime: "17:00",
    duration: "7h",
    price: 600,
    availableSeats: 25,
  },
  {
    id: "FL005",
    airline: "Qantas",
    departureCity: "Sydney",
    arrivalCity: "Singapore",
    departureDate: "2024-09-05",
    departureTime: "13:30",
    arrivalTime: "18:00",
    duration: "7h 30m",
    price: 700,
    availableSeats: 15,
  },
  {
    id: "FL006",
    airline: "Emirates",
    departureCity: "Dubai",
    arrivalCity: "Cape Town",
    departureDate: "2024-09-06",
    departureTime: "22:00",
    arrivalTime: "06:00",
    duration: "8h",
    price: 800,
    availableSeats: 18,
  },
  {
    id: "FL007",
    airline: "Singapore Airlines",
    departureCity: "Singapore",
    arrivalCity: "San Francisco",
    departureDate: "2024-09-07",
    departureTime: "12:00",
    arrivalTime: "16:00",
    duration: "16h",
    price: 1200,
    availableSeats: 10,
  },
  {
    id: "FL008",
    airline: "Cathay Pacific",
    departureCity: "Hong Kong",
    arrivalCity: "Sydney",
    departureDate: "2024-09-08",
    departureTime: "23:00",
    arrivalTime: "10:00",
    duration: "9h",
    price: 650,
    availableSeats: 14,
  },
  {
    id: "FL009",
    airline: "American Airlines",
    departureCity: "Miami",
    arrivalCity: "Mexico City",
    departureDate: "2024-09-09",
    departureTime: "08:00",
    arrivalTime: "10:30",
    duration: "2h 30m",
    price: 250,
    availableSeats: 22,
  },
  {
    id: "FL010",
    airline: "Turkish Airlines",
    departureCity: "Istanbul",
    arrivalCity: "Moscow",
    departureDate: "2024-09-10",
    departureTime: "07:00",
    arrivalTime: "09:00",
    duration: "2h",
    price: 400,
    availableSeats: 30,
  },
  {
    id: "FL011",
    airline: "Qatar Airways",
    departureCity: "Doha",
    arrivalCity: "Bangkok",
    departureDate: "2024-09-11",
    departureTime: "01:00",
    arrivalTime: "07:00",
    duration: "6h",
    price: 550,
    availableSeats: 20,
  },
  {
    id: "FL012",
    airline: "Virgin Atlantic",
    departureCity: "London",
    arrivalCity: "Johannesburg",
    departureDate: "2024-09-12",
    departureTime: "20:00",
    arrivalTime: "06:00",
    duration: "10h",
    price: 850,
    availableSeats: 17,
  },
  {
    id: "FL013",
    airline: "Aeroflot",
    departureCity: "Moscow",
    arrivalCity: "Beijing",
    departureDate: "2024-09-13",
    departureTime: "10:00",
    arrivalTime: "20:00",
    duration: "8h",
    price: 700,
    availableSeats: 12,
  },
  {
    id: "FL014",
    airline: "KLM",
    departureCity: "Amsterdam",
    arrivalCity: "Nairobi",
    departureDate: "2024-09-14",
    departureTime: "08:30",
    arrivalTime: "18:00",
    duration: "8h 30m",
    price: 650,
    availableSeats: 15,
  },
  {
    id: "FL015",
    airline: "Iberia",
    departureCity: "Madrid",
    arrivalCity: "Buenos Aires",
    departureDate: "2024-09-15",
    departureTime: "22:00",
    arrivalTime: "09:00",
    duration: "13h",
    price: 950,
    availableSeats: 8,
  },
  {
    id: "FL016",
    airline: "Southwest Airlines",
    departureCity: "Los Angeles",
    arrivalCity: "Las Vegas",
    departureDate: "2024-09-16",
    departureTime: "10:00",
    arrivalTime: "11:00",
    duration: "1h",
    price: 150,
    availableSeats: 25,
  },
  {
    id: "FL017",
    airline: "Air Canada",
    departureCity: "Toronto",
    arrivalCity: "Vancouver",
    departureDate: "2024-09-17",
    departureTime: "12:00",
    arrivalTime: "14:00",
    duration: "2h",
    price: 200,
    availableSeats: 18,
  },
  {
    id: "FL018",
    airline: "Avianca",
    departureCity: "Bogota",
    arrivalCity: "Lima",
    departureDate: "2024-09-18",
    departureTime: "07:00",
    arrivalTime: "09:00",
    duration: "2h",
    price: 300,
    availableSeats: 22,
  },
  {
    id: "FL019",
    airline: "Etihad Airways",
    departureCity: "Abu Dhabi",
    arrivalCity: "Sydney",
    departureDate: "2024-09-19",
    departureTime: "22:00",
    arrivalTime: "06:00",
    duration: "14h",
    price: 1100,
    availableSeats: 10,
  },
  {
    id: "FL020",
    airline: "Thai Airways",
    departureCity: "Bangkok",
    arrivalCity: "Tokyo",
    departureDate: "2024-09-20",
    departureTime: "08:00",
    arrivalTime: "16:00",
    duration: "8h",
    price: 750,
    availableSeats: 16,
  },
  {
    id: "FL021",
    airline: "Alitalia",
    departureCity: "Rome",
    arrivalCity: "Athens",
    departureDate: "2024-09-21",
    departureTime: "09:00",
    arrivalTime: "11:00",
    duration: "2h",
    price: 180,
    availableSeats: 28,
  },
  {
    id: "FL022",
    airline: "Ethiopian Airlines",
    departureCity: "Addis Ababa",
    arrivalCity: "Johannesburg",
    departureDate: "2024-09-22",
    departureTime: "15:00",
    arrivalTime: "19:00",
    duration: "4h",
    price: 350,
    availableSeats: 20,
  },
  {
    id: "FL023",
    airline: "Garuda Indonesia",
    departureCity: "Jakarta",
    arrivalCity: "Bali",
    departureDate: "2024-09-23",
    departureTime: "06:00",
    arrivalTime: "08:00",
    duration: "2h",
    price: 220,
    availableSeats: 24,
  },
  {
    id: "FL024",
    airline: "Malaysia Airlines",
    departureCity: "Kuala Lumpur",
    arrivalCity: "Melbourne",
    departureDate: "2024-09-24",
    departureTime: "12:00",
    arrivalTime: "21:00",
    duration: "9h",
    price: 700,
    availableSeats: 12,
  },
  {
    id: "FL025",
    airline: "ANA",
    departureCity: "Tokyo",
    arrivalCity: "Los Angeles",
    departureDate: "2024-09-25",
    departureTime: "16:00",
    arrivalTime: "09:00",
    duration: "11h",
    price: 900,
    availableSeats: 14,
  },
  {
    id: "FL026",
    airline: "Air India",
    departureCity: "Delhi",
    arrivalCity: "London",
    departureDate: "2024-09-26",
    departureTime: "10:00",
    arrivalTime: "14:00",
    duration: "9h",
    price: 850,
    availableSeats: 10,
  },
  {
    id: "FL027",
    airline: "Swiss International Air Lines",
    departureCity: "Zurich",
    arrivalCity: "Paris",
    departureDate: "2024-09-27",
    departureTime: "11:00",
    arrivalTime: "12:00",
    duration: "1h",
    price: 200,
    availableSeats: 25,
  },
  {
    id: "FL028",
    airline: "Scandinavian Airlines",
    departureCity: "Copenhagen",
    arrivalCity: "Oslo",
    departureDate: "2024-09-28",
    departureTime: "07:30",
    arrivalTime: "08:30",
    duration: "1h",
    price: 150,
    availableSeats: 30,
  },
  {
    id: "FL029",
    airline: "Aeromexico",
    departureCity: "Mexico City",
    arrivalCity: "Cancun",
    departureDate: "2024-09-29",
    departureTime: "13:00",
    arrivalTime: "15:00",
    duration: "2h",
    price: 180,
    availableSeats: 22,
  },
  {
    id: "FL030",
    airline: "Copa Airlines",
    departureCity: "Panama City",
    arrivalCity: "Bogota",
    departureDate: "2024-09-30",
    departureTime: "16:00",
    arrivalTime: "18:00",
    duration: "2h",
    price: 220,
    availableSeats: 18,
  },
  {
    id: "FL031",
    airline: "EgyptAir",
    departureCity: "Cairo",
    arrivalCity: "Dubai",
    departureDate: "2024-10-01",
    departureTime: "12:00",
    arrivalTime: "18:00",
    duration: "4h",
    price: 500,
    availableSeats: 20,
  },
  {
    id: "FL032",
    airline: "Vueling Airlines",
    departureCity: "Barcelona",
    arrivalCity: "Rome",
    departureDate: "2024-10-02",
    departureTime: "09:00",
    arrivalTime: "11:00",
    duration: "2h",
    price: 180,
    availableSeats: 28,
  },
  {
    id: "FL033",
    airline: "SAS",
    departureCity: "Stockholm",
    arrivalCity: "Helsinki",
    departureDate: "2024-10-03",
    departureTime: "14:00",
    arrivalTime: "16:00",
    duration: "2h",
    price: 200,
    availableSeats: 25,
  },
  {
    id: "FL034",
    airline: "LATAM Airlines",
    departureCity: "Santiago",
    arrivalCity: "Lima",
    departureDate: "2024-10-04",
    departureTime: "08:00",
    arrivalTime: "11:00",
    duration: "3h",
    price: 350,
    availableSeats: 18,
  },
  {
    id: "FL035",
    airline: "GOL Airlines",
    departureCity: "Rio de Janeiro",
    arrivalCity: "Sao Paulo",
    departureDate: "2024-10-05",
    departureTime: "07:00",
    arrivalTime: "08:00",
    duration: "1h",
    price: 120,
    availableSeats: 20,
  },
  {
    id: "FL036",
    airline: "Asiana Airlines",
    departureCity: "Seoul",
    arrivalCity: "Hong Kong",
    departureDate: "2024-10-06",
    departureTime: "23:00",
    arrivalTime: "03:00",
    duration: "4h",
    price: 600,
    availableSeats: 15,
  },
  {
    id: "FL037",
    airline: "TAP Portugal",
    departureCity: "Lisbon",
    arrivalCity: "Newark",
    departureDate: "2024-10-07",
    departureTime: "15:00",
    arrivalTime: "20:00",
    duration: "8h",
    price: 700,
    availableSeats: 10,
  },
  {
    id: "FL038",
    airline: "Emirates",
    departureCity: "Dubai",
    arrivalCity: "Paris",
    departureDate: "2024-10-08",
    departureTime: "02:00",
    arrivalTime: "08:00",
    duration: "6h",
    price: 800,
    availableSeats: 20,
  },
  {
    id: "FL039",
    airline: "Vietnam Airlines",
    departureCity: "Hanoi",
    arrivalCity: "Ho Chi Minh City",
    departureDate: "2024-10-09",
    departureTime: "10:00",
    arrivalTime: "12:00",
    duration: "2h",
    price: 250,
    availableSeats: 22,
  },
  {
    id: "FL040",
    airline: "Air New Zealand",
    departureCity: "Auckland",
    arrivalCity: "Sydney",
    departureDate: "2024-10-10",
    departureTime: "07:00",
    arrivalTime: "09:00",
    duration: "3h",
    price: 500,
    availableSeats: 12,
  },
];
