//http://localhost:3000/description/presentation
import BreadcrumbHotel from '@/components/Description/Breadcrumb';
import Equipment from '@/components/Description/Equipment';
import GridImg from '@/components/Description/GridImg';
import NavDescription from '@/components/Description/NavDescription';
import Footer from '@/components/Footer';
import GetstartSearch from '@/components/GetstartSearch';
import Navbar from '@/components/Navbar';
import { Breadcrumb } from '@/components/ui/breadcrumb';
import { Bus, BicepsFlexed, EggFried, Hotel } from 'lucide-react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { FaSpa, FaUmbrellaBeach } from 'react-icons/fa';
import { PiSwimmingPoolDuotone } from 'react-icons/pi';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <section className="mx-auto container">
          <GetstartSearch />
          <BreadcrumbHotel />
          <section className="mt-4">
            <GridImg />
          </section>
          <NavDescription />

          {children}
        </section>
        <Footer />
      </body>
    </html>
  );
}
